services:
  spark-jupyter:
    build: .
    ports:
      - "8888:8888"
    environment:
      - SPARK_MODE=local
      - SPARK_MASTER_URL=spark://localhost:7077
      - JUPYTER_TOKEN=spark
    volumes:
      - ../Demos:/home/jovyan/work/demos
      - ../Labs:/home/jovyan/work/labs
      - ../Soluciones:/home/jovyan/work/solutions
      - ../Datasets:/home/jovyan/work/datasets
    working_dir: /home/jovyan/work

